---
# tasks file for proftpd
- name: Install ProFTPd Packages
  apt: name=proftpd state=latest update_cache=yes

- name: Copy Configuration file
  copy:
    src: files/proftpd.conf
    dest: /etc/proftpd/proftpd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart proftpd

- name: Creating /usr/local/bin/ftponly shell
  file:
    path: /usr/local/bin/ftponly
    state: touch

- name: Adding /usr/local/bin/ftponly to valid system shells
  lineinfile:
    path: /etc/shells
    line: '/usr/local/bin/ftponly'
